"use client";

import { useState } from "react";
import "./owner.css";

const slips = [
  { customer: "คุณกานต์ธิดา ว.", contract: "CG-2025-0418", amount: "562.50", time: "วันนี้ · 10:24" },
  { customer: "คุณพงศ์ภัทร ร.", contract: "CG-2025-0406", amount: "750.00", time: "วันนี้ · 09:42" },
];

export default function OwnerDashboard() {
  const [rate, setRate] = useState("1.25");
  const [saved, setSaved] = useState(false);
  const [tab, setTab] = useState("ภาพรวม");
  const limitExceeded = Number(rate) > 1.25;
  const save = () => { setSaved(true); window.setTimeout(() => setSaved(false), 2200); };
  return <main className="owner-shell">
    <aside className="sidebar"><div className="owner-brand"><span>✦</span><div>ทองดี<small>สำหรับเจ้าของร้าน</small></div></div><nav>{["ภาพรวม", "สัญญาขายฝาก", "ลูกค้า", "ตรวจสลิป", "รายงาน"].map((item, index) => <button key={item} onClick={() => setTab(item)} className={tab === item ? "nav-active" : ""}><span>{["▦", "▤", "♙", "▧", "◫"][index]}</span>{item}{item === "ตรวจสลิป" && <b>2</b>}</button>)}</nav><div className="sidebar-bottom"><button onClick={() => setTab("ตั้งค่าร้าน")}><span>⚙</span>ตั้งค่าร้าน</button><button><span>↪</span>ออกจากระบบ</button><div className="shop-profile"><i>ท</i><p><strong>ร้านทองทองดี</strong><small>ผู้ดูแลระบบ</small></p></div></div></aside>
    <section className="owner-content"><header className="owner-top"><div><p>{tab === "ภาพรวม" ? "ภาพรวมร้าน" : tab}</p><h1>{tab === "ภาพรวม" ? "สวัสดีครับ, คุณธนา" : tab}</h1></div><div><button className="notification">♢<b>2</b></button><button className="new-contract">＋ สร้างสัญญาขายฝาก</button></div></header>{tab === "ตั้งค่าร้าน" ? <Settings rate={rate} setRate={setRate} limitExceeded={limitExceeded} saved={saved} save={save} /> : <Overview />}</section>
  </main>;
}

function Overview() { return <><section className="owner-stats"><Stat icon="▤" label="สัญญาที่ยังใช้งาน" value="248" note="+12 จากเดือนก่อน" /><Stat icon="฿" label="ยอดขายฝากคงค้าง" value="8,425,000" unit="บาท" note="อัปเดตล่าสุดวันนี้" /><Stat icon="◷" label="ค่าขยายเวลารอชำระ" value="12,480" unit="บาท" note="18 สัญญาใกล้ครบกำหนด" /><Stat icon="▧" label="สลิปรอตรวจสอบ" value="2" unit="รายการ" note="ต้องดำเนินการวันนี้" /></section><section className="owner-grid"><article className="panel"><PanelTitle overline="ติดตามสัญญา" title="ใกล้ครบกำหนดไถ่ถอน" count="18" /><Deadline date="18" customer="คุณกานต์ธิดา ว." contract="CG-2025-0418 · ทองรูปพรรณ 1 บาท" amount="45,000 บาท" remaining="เหลือ 7 วัน" /><Deadline date="20" customer="คุณอรุณี พ." contract="CG-2025-0399 · ทองรูปพรรณ 2 บาท" amount="68,500 บาท" remaining="เหลือ 9 วัน" /></article><article className="panel"><PanelTitle overline="การชำระเงิน" title="สลิปรอตรวจสอบ" count="2" />{slips.map((slip) => <div className="slip" key={slip.contract}><i>▧</i><div><strong>{slip.customer}</strong><p>{slip.contract} · {slip.time}</p></div><div><b>{slip.amount} บาท</b><button>ตรวจสอบ</button></div></div>)}</article></section><section className="panel recent"><PanelTitle overline="รายการล่าสุด" title="สัญญาขายฝากล่าสุด" /><div className="table"><div className="table-head"><span>เลขที่สัญญา</span><span>ลูกค้า</span><span>ยอดขายฝาก</span><span>วันครบกำหนดไถ่ถอน</span><span>สถานะ</span></div><div><strong>CG-2025-0421</strong><span>คุณศุภชัย ม.</span><b>32,000 บาท</b><span>21 ก.ค. 2568</span><em>ใช้งานอยู่</em></div><div><strong>CG-2025-0420</strong><span>คุณวิภาดา ช.</span><b>75,000 บาท</b><span>20 ก.ค. 2568</span><em>ใช้งานอยู่</em></div></div></section></> }
function Settings({ rate, setRate, limitExceeded, saved, save }: { rate: string; setRate: (v: string) => void; limitExceeded: boolean; saved: boolean; save: () => void }) { return <section className="settings-panel"><div className="settings-title"><i>⚙</i><div><h2>ตั้งค่าร้านทองทองดี</h2><p>จัดการข้อมูลร้าน บัญชีรับเงิน และอัตราค่าขยายเวลาไถ่ถอน</p></div></div><div className="setting-row"><div><h3>อัตราค่าขยายเวลาไถ่ถอน</h3><p>ใช้คำนวณค่าขยายเวลาไถ่ถอนสำหรับสัญญาขายฝากใหม่</p></div><label>อัตราต่อเดือน<div className="rate-input"><input type="number" min="0" step="0.01" value={rate} onChange={(e) => setRate(e.target.value)} /><span>%</span></div></label>{limitExceeded && <strong className="warning">⚠ อัตราที่ตั้งสูงกว่าแนวทาง 1.25% ต่อเดือน กรุณาตรวจสอบข้อตกลงในสัญญา</strong>}<small className="guide">แนวทางอัตราค่าขยายเวลาไถ่ถอน: ไม่ควรเกิน 1.25% ต่อเดือน หรือ 15% ต่อปี</small></div><div className="setting-row"><div><h3>บัญชีธนาคารรับเงิน</h3><p>แสดงให้ลูกค้าโอนค่าขยายเวลาไถ่ถอน</p></div><div className="bank-card"><i>K+</i><p><b>ธนาคารกสิกรไทย</b><small>xxx-x-12345-x · ร้านทองทองดี</small></p><button>แก้ไข</button></div></div><div className="save-row"><button className="cancel">ยกเลิก</button><button className="save" onClick={save}>{saved ? "✓ บันทึกเรียบร้อย" : "บันทึกการตั้งค่า"}</button></div></section> }
function Stat({ icon, label, value, unit, note }: { icon: string; label: string; value: string; unit?: string; note: string }) { return <article className="stat"><i>{icon}</i><p>{label}</p><strong>{value} <small>{unit}</small></strong><em>{note}</em></article>; }
function PanelTitle({ overline, title, count }: { overline: string; title: string; count?: string }) { return <div className="panel-title"><div><p>{overline}</p><h2>{title} {count && <span>{count}</span>}</h2></div><button>ดูทั้งหมด →</button></div>; }
function Deadline({ date, customer, contract, amount, remaining }: { date: string; customer: string; contract: string; amount: string; remaining: string }) { return <div className="deadline"><i><b>{date}</b><small>มิ.ย. 2568</small></i><div><strong>{customer}</strong><p>{contract}</p></div><div><b>{amount}</b><small>{remaining}</small></div><button>→</button></div>; }
